name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Gofumpt
        run: go install mvdan.cc/gofumpt@latest && gofumpt -l -w .

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1

      - name: Build
        run: go build -v ./...

      - name: Tests
        run: go test -v ./...
